version: '3.9'

services:
  postgres:
    container_name: ${PROJECT_NAME}-pg
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${TYPEORM_PORT}:5432
    networks:
      - network
    restart: unless-stopped

volumes:
  postgres:

networks:
  network:
    driver: bridge
